[[redirects]]
  from = "sogyalsherpa.tech"
  to = "sogyalsherpa.com"
  status = 301
  force = true

[[redirects]]
  from = "www.sogyalsherpa.tech"
  to = "sogyalsherpa.com"
  status = 301
  force = true